Fix unittest assert calls for Python 3.12
django-haystack/django-haystack pull request #1930
Opened 2023-12-31 15:12 UTC by cclauss

Fix `unittest` assert calls for Python 3.12: https://docs.python.org/3/whatsnew/3.12.html#id3

2023-12-31 15:30 UTC, claudep requested changes

2023-12-31 15:30 UTC, claudep commented on test_haystack/test_managers.py
> +        self.assertTrue(isinstance(sqs, ValuesSearchQuerySet))
We can use assertIsInstance instead, same below.

2023-12-31 15:30 UTC, claudep commented on test_haystack/test_query.py
> +        self.assertTrue(flat_sqs[0:1][0] is None)
`assertIsNone` comes to mind.

2023-12-31 15:45 UTC, cclauss commented on test_haystack/test_managers.py
> +        self.assertTrue(isinstance(sqs, ValuesSearchQuerySet))
;-)  This is why most Python developers are delighted to drop all these different methods and allow pytest to take full advantage of assert rewriting.

2024-01-01 08:16 UTC, cclauss commented
@claudep Why disable auto-merge on this PR?  Is there something controversial about the proposed changes?

2024-01-01 18:52 UTC, claudep approved these changes

2024-01-01 18:53 UTC, merged